[package]
name = "Debounce_Software"
version = "0.1.0"
edition = "2021"

[dependencies]
evdev = "0.13.1"
nix = { version = "0.30.1", features = ["user"] }
log = "0.4.27"
env_logger = "0.11.8"
#nix = "0.30.1"
